# Generated by Django 3.0.7 on 2020-10-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
