# Generated by Django 3.0.7 on 2020-11-07 22:29

import Administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_auto_20201013_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=Administration.models.upload_avatar_to, verbose_name='profile picture'),
        ),
    ]
