# Generated by Django 3.0.7 on 2020-11-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_member_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
