# Generated by Django 3.0.7 on 2020-11-12 05:59

import Administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_auto_20201108_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='avatar_images/DefaultImage.png', upload_to=Administration.models.upload_avatar_to, verbose_name='profile picture'),
        ),
    ]
