# Generated by Django 3.0.7 on 2020-12-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0007_auto_20201111_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
