# Generated by Django 3.1.3 on 2020-12-31 01:56

import Sponsors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, upload_to=Sponsors.models.upload_Sponsor_Logo, verbose_name='Sponsor Logo')),
            ],
        ),
    ]
