# Generated by Django 3.1.3 on 2020-12-31 02:24

import Sponsors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Diamond'), (1, 'Gold'), (2, 'Silver'), (3, 'Bronze')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to=Sponsors.models.upload_Sponsor_Logo, verbose_name='Sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
