# Generated by Django 3.0.7 on 2020-12-10 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reigon', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('president', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField()),
                ('website', models.URLField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommunityChapters.Country')),
            ],
        ),
    ]
