# Generated by Django 3.1.5 on 2021-01-25 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20210123_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='name',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='action',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='competition',
            name='description_field_number_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='description_field_number_2',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='description_field_number_3',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='description_field_number_4',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='description_field_text_1',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='description_field_text_2',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='description_field_text_3',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='description_field_text_4',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
