# Generated by Django 3.0.7 on 2020-12-08 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administration', '0008_member_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Management', 'Management'), ('Web Development', 'Web Development'), ('Finance', 'Finance'), ('Graphic Design', 'Graphic Design'), ('Marketing', 'Marketing'), ('Human Resources', 'Human Resources'), ('Writing', 'Writing')], max_length=50)),
                ('subposition', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administration.Member')),
            ],
        ),
    ]
