# Generated by Django 3.1.3 on 2021-01-01 18:39

import Subsidiaries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, upload_to=Subsidiaries.models.upload_Subsidiary_Logo, verbose_name='Partner Logo')),
            ],
        ),
    ]
