# Generated by Django 3.0.7 on 2021-01-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subsidiaries', '0002_auto_20210101_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
