# Generated by Django 3.1.3 on 2021-06-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subsidiaries', '0003_auto_20210102_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='IconCardBGColor',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='tag',
            field=models.IntegerField(choices=[(0, 'Standard'), (1, 'Beta'), (2, 'Down')], default=0),
        ),
    ]
