# Generated by Django 3.2.5 on 2021-07-20 13:45

from django.db import migrations, models
import interstellar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Funding_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Internship_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('logo', models.ImageField(blank=True, upload_to=interstellar.models.upload_Opportunity_img, verbose_name='Opportunity Logo')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('tags', models.ManyToManyField(to='interstellar.Opportunity_Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('logo', models.ImageField(blank=True, upload_to=interstellar.models.upload_Internship_img, verbose_name='Internship Logo')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('tags', models.ManyToManyField(to='interstellar.Internship_Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('amount', models.BigIntegerField()),
                ('description', models.TextField()),
                ('duedate', models.DateField()),
                ('type', models.IntegerField(choices=[(0, 'Individual'), (1, 'Team')])),
                ('link', models.URLField()),
                ('tags', models.ManyToManyField(to='interstellar.Funding_Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('logo', models.ImageField(blank=True, upload_to=interstellar.models.upload_Competition_img, verbose_name='Competition Logo')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('tags', models.ManyToManyField(to='interstellar.Competition_Tag')),
            ],
        ),
    ]
