# Generated by Django 3.0.7 on 2020-10-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20201012_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.FileField(default=0, upload_to='TeamIcons'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(upload_to='ProjectIcons'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='Thumbnails'),
        ),
    ]
