# Generated by Django 3.0.7 on 2020-10-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20201012_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(max_length=40),
        ),
    ]
