# Generated by Django 3.0.7 on 2020-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20201013_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='icon',
            field=models.URLField(blank=True),
        ),
    ]
