# Generated by Django 3.0.7 on 2020-10-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_auto_20201013_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Desc1Image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Desc2Image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Desc3Image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='LongDesc1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='LongDesc2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='LongDesc3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
