# Generated by Django 3.0.7 on 2020-10-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_auto_20201013_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Desc1Title',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Desc2Title',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Desc3Title',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
