# Generated by Django 3.0.7 on 2020-11-07 22:59

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0011_auto_20201013_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Desc1Image',
            field=models.ImageField(blank=True, upload_to=Projects.models.upload_Project_Images, verbose_name='Project Images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Desc2Image',
            field=models.ImageField(blank=True, upload_to=Projects.models.upload_Project_Images, verbose_name='Project Images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Desc3Image',
            field=models.ImageField(blank=True, upload_to=Projects.models.upload_Project_Images, verbose_name='Project Images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, upload_to=Projects.models.upload_Project_Logo, verbose_name='Project Logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=Projects.models.upload_Project_Thumbnail, verbose_name='Project Thumbnail'),
        ),
        migrations.AlterField(
            model_name='team',
            name='icon',
            field=models.ImageField(blank=True, upload_to=Projects.models.upload_Team_Logo, verbose_name='Team Logo'),
        ),
    ]
