# Generated by Django 3.0.7 on 2020-12-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_member_xp'),
        ('Projects', '0012_auto_20201107_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lead', models.CharField(default='Member', max_length=50)),
                ('Team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Projects.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roles', models.ManyToManyField(to='Projects.TeamRole')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administration.Member')),
            ],
        ),
    ]
