# Generated by Django 3.0.7 on 2020-12-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_member_xp'),
        ('Projects', '0013_auto_20201210_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrole',
            name='User',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Administration.Member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamrole',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Team'),
        ),
        migrations.DeleteModel(
            name='TeamLead',
        ),
    ]
