# Generated by Django 3.0.7 on 2020-12-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_member_xp'),
        ('Projects', '0014_auto_20201210_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='Administration.Member'),
        ),
    ]
