# Generated by Django 3.0.7 on 2021-01-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0015_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='PaperURL',
            field=models.URLField(blank=True),
        ),
    ]
