# Generated by Django 3.1.3 on 2021-02-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0009_member_discordid'),
        ('Projects', '0016_project_paperurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamrole',
            old_name='Lead',
            new_name='Title',
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Member', max_length=50)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administration.member')),
            ],
        ),
    ]
