# Generated by Django 3.1.3 on 2021-06-01 16:45

import Projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0019_auto_20210205_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='inner_icon',
            field=models.ImageField(blank=True, upload_to=Projects.models.upload_Team_Logo_inner, verbose_name='Team Logo Inner'),
        ),
    ]
