# Generated by Django 3.1.3 on 2021-06-16 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0020_team_inner_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='IconCardBGColor',
            field=models.CharField(default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
    ]
