# Generated by Django 3.1.3 on 2021-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0021_team_iconcardbgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='IconCardBGColor',
            field=models.CharField(max_length=6),
        ),
    ]
