# Generated by Django 3.2.6 on 2021-10-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0023_auto_20210616_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
