# Generated by Django 3.0.7 on 2020-11-07 18:25

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20201107_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='thumbnail_desc',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_desc', wagtail.core.blocks.TextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock())], blank=True),
        ),
    ]
