# Generated by Django 3.0.7 on 2020-11-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20201107_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('Events', 'Events'), ('Partners', 'Partners')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
