# Generated by Django 3.0.7 on 2020-11-08 06:03

import Blog.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blogpage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=Blog.models.upload_Thumbnail, verbose_name='Thumbnail'),
        ),
    ]
