# Generated by Django 3.0.7 on 2020-11-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20201111_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
