# Generated by Django 3.0.7 on 2020-12-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_blogpage_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='OrginizationLink',
            field=models.URLField(default='https://novacrypt.org/'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='OrginizationName',
            field=models.CharField(default='Novacrypt', max_length=100),
        ),
    ]
