# Generated by Django 3.0.7 on 2020-12-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20201207_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='OrginizationName',
            field=models.CharField(default='NovaCrypt', max_length=100),
        ),
    ]
