# Generated by Django 3.2.6 on 2021-10-09 23:19

import NRI.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administration', '0009_member_discordid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('logo', models.ImageField(blank=True, upload_to=NRI.models.upload_Course_Logo, verbose_name='Course Logo')),
                ('members', models.ManyToManyField(blank=True, to='Administration.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('order', models.PositiveIntegerField(default=1)),
                ('thumbnail', models.URLField()),
                ('link', models.URLField()),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='NRI.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
