# Generated by Django 3.2.6 on 2021-10-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NRI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='video',
            name='video_code',
            field=models.CharField(default='abc', max_length=35),
            preserve_default=False,
        ),
    ]
