# Generated by Django 3.1.3 on 2020-12-30 23:39

import Partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, upload_to=Partners.models.upload_Partner_Logo, verbose_name='Partner Logo')),
            ],
        ),
    ]
