# Generated by Django 3.2.5 on 2021-07-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('tag', models.IntegerField(choices=[(0, 'Standard'), (1, 'Beta'), (2, 'Down')], default=0)),
                ('link', models.URLField()),
            ],
        ),
    ]
