# Generated by Django 3.2.5 on 2021-07-23 13:21

import Landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('logo', models.ImageField(blank=True, upload_to=Landing.models.upload_News_Logo, verbose_name='News Logo')),
                ('desc', models.TextField()),
            ],
        ),
    ]
