# Generated by Django 3.2.6 on 2021-10-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
